# Generated by Django 2.1.7 on 2019-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addr_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
    ]
